build:
	@(docker build  -t jeduoliveira/lumisxp:10.3.1.171215-freeversion-centos-7-openjdk-8  .)


build-free:
	@(docker build  -t jeduoliveira/lumisxp:10.3.1.171215-freeversion-centos-7-openjdk-8  .)
	
push-free: build-free
	docker push jeduoliveira/lumisxp:10.3.1.171215-freeversion-centos-7-openjdk-8
	
	
	


