
build:
	docker build  -t jeduoliveira/lumisxp:12.4.0-freeversion-alpine  --build-arg LUMIS_VERSION=12.4.0.200625-FreeVersion .

push: build
	docker push jeduoliveira/lumisxp:12.4.0-freeversion-alpine